### ISSUE TITLE
Pointer to refactored code base of react-slick

### ISSUE THREAD

**Issue by jonathanglasmeyer** [akiran/neo-react-slider#1]
Hi @akiran. We've been using react-slick for https://wish.technology/en/features . After noticing that interaction on the react-slick repo is not really happening, we [forked](https://github.com/wish-technology/react-slick) the repo in order to integrate some necessary changes, refactoring the code base to ES2015/next on the way. I now see that you're probably starting a rewrite here and just wanted to give you a pointer to that refactored code base, _in case_ you plan to reuse some of your old code in this project -- maybe it could save you some work. :)

I'd be happy to help if you want to split up the work.
Cheers, Jonathan

**Comment by akiran** [comment]
@jonathanewerner  This is not a re-write for react-slick. I am trying to implement a range slider here.

You can suggest improvements and open PR's for react-slick repo

**Comment by jonathanglasmeyer** [comment]
Ok, my bad. :)
